user_client:
	kitex -I ../../idl/ -module github.com/weirdo0314/tiny-tiktok -type protobuf -service  userservice ../../idl/user.proto

video_client:
	kitex -I ../../idl/ -module github.com/weirdo0314/tiny-tiktok -type protobuf -service  videoservice ../../idl/video.proto